### ISSUE TITLE
Undercurl text are converted to strikethrough text

### ISSUE THREAD

**Issue by SafetyMary** [maxmx03/solarized.nvim#102]
When i turn on spell check, undercurl text (indicating wrong spelling) are converted to strickthrough.

![image](https://github.com/user-attachments/assets/cfad1ce9-f9f7-40c1-8612-b36b79ce7a12)

**Comment by SafetyMary** [comment]
Sorry, it seems to be a wezterm related issue. Not related to the color scheme

**Comment by mtrudel** [comment]
Any insight here @SafetyMary ? I'm getting this now too but don't use Wezterm (plain old iTerm over here).

**Comment by SafetyMary** [comment]
The issue usually lies in terminal undercurl support. Make sure your terminal, terminal multiplexer (e.g. tmux) and your application (e.g. neovim) supports undercurl. Some terminals would need specific config to handle undercruls. In my case there is no quick fix and i just live with it

**Comment by mtrudel** [comment]
Thanks! 

FWIW, my fix was / is to pin solarized.nvim to v3.0.0 - anything newer than that breaks not only under curl but a bunch of other colours, and i honestly can't be bothered to spend that much time trying to fix it.

**Comment by alexandrebelloni** [comment]
This is caused by 5b304a17ae992 which explicitely move from:

`set_hl('SpellBad', { sp = c.red, undercurl = true }) -- Word that is not recognized by the spellchecker.
`
to:

`nvim_set_hl('SpellBad', { underline = true, strikethrough = true })
`

**Comment by alexandrebelloni** [comment]
This fixed it locally for me:

```
lvim.autocommands = {
  {
    { "ColorScheme" },
    {
      pattern = "*",
      callback = function()
        vim.api.nvim_set_hl(0, "SpellBad", { sp = '#DC322F', undercurl = true })
        vim.api.nvim_set_hl(0, "SpellCap", { sp = '#6C71C4', undercurl = true })
        vim.api.nvim_set_hl(0, "SpellLocal", { sp = '#B58900', undercurl = true })
        vim.api.nvim_set_hl(0, "SpellRare", { sp = '#2AA198', undercurl = true })
      end,
    },
  },
}
```

**Comment by alexandrebelloni** [comment]
This is also working:

```
require('solarized').setup {
    on_highlights = function (colors, color)

        ---@type solarized.highlights
        local groups = {
            SpellBad = { underline = false, strikethrough = false, sp = colors.red, undercurl = true },
            SpellCap =  { sp = colors.violet, undercurl = true },
            SpellLocal = { sp = colors.yellow, undercurl = true },
            SpellRare =  { sp = colors.cyan, undercurl = true },
        }

       return groups
    end
}
```
