### ISSUE TITLE
Strange conflict colors in light theme

### ISSUE THREAD

**Issue by parsiad** [maxmx03/solarized.nvim#103]
Hi,

Thank you for the great colorscheme.

I am getting strange conflict colors that make it hard to read with the light version of the colorscheme:

![image](https://github.com/user-attachments/assets/3aca4940-b8d1-400b-bc6b-0d21ed395836)

My lazy.nvim config: 

```lua
return {
  "maxmx03/solarized.nvim",
  lazy = false,
  priority = 1000,
  config = function()
    vim.o.background = "light"
    vim.cmd.colorscheme("solarized")
    vim.cmd("hi Normal guibg=NONE ctermbg=NONE")
  end,
}
```

Here is the default colorscheme for comparison:

![image](https://github.com/user-attachments/assets/174cc165-4017-482c-916e-73818463d28e)

**Comment by maxmx03** [comment]
Are you using any specific plugin?
Try adjusting the following highlight groups to see if it resolves your issue:

```txt
Added
Changed
Removed

DiffAdd
DiffChange
DiffDelete
DiffText
```

```lua
require('solarized').setup {
    on_highlights = function (colors, color)
        ---@type solarized.highlights
        local groups = {
            Added = { fg = colors.green },
            -- Added = { link = 'DiffAdd' },
            -- ...
        }

       return groups
    end
}
```

**Comment by parsiad** [comment]
You are correct; it was unrelated to solarized.nvim. Sorry about that!
