### ISSUE TITLE
background color changed after jump into hover infomation

### ISSUE THREAD

**Issue by ShiChenCong** [maxmx03/solarized.nvim#17]
Thank you for the work.
Plugin works fine when my cursor is here
![image](https://user-images.githubusercontent.com/22486446/223649079-e7614616-70b3-4de9-adbd-9cc118a72648.png)
but, background color changed when i jump into here
![image](https://user-images.githubusercontent.com/22486446/223649187-9ca1c555-a127-4a1a-9b9a-27cae4ef7fa7.png)

**Comment by maxmx03** [comment]
This is the expected behavior, but you can change it. Here's how

```lua
solarized:setup {
      config = {
        theme = 'neovim',
        transparent = false
      },
      highlights = function()
        return { 
          NormalNC = { link = 'Normal' }
        }
      end
  }
```

Alternatively, you can switch to the VSCode theme:

```lua
solarized:setup {
      config = {
        theme = 'vscode',
        transparent = false
      }
  }
```

**Comment by ShiChenCong** [comment]
It works,Thank you for your detailed reply.
