### ISSUE TITLE
[Feature] Add accessor for default colors

### ISSUE THREAD

**Issue by vihu** [maxmx03/solarized.nvim#19]
Hello,

Thank you for making an awesome treesitter supported solarized colorscheme (I had been looking for a while!)!

I wanted to try something like:

```
        solarized:setup({
            config = {
                theme = "neovim",
                transparent = true,
                highlights = function(colors, darken, _, _)
                    return {
                        NormalNC = { bg = colors.bg, fg = darken(colors.fg, 10) },
                    }
                end,
            },
        })

``` 

Basically lighten/darken a non-active window/split, but there doesn't seem to be a straightforward way to access the default color palette. Can you please advise? It would be nice if something like `solarized.colors` (or something similar) was readily available so I can just adjust without specifying a custom colors table.

Thanks!

**Comment by maxmx03** [comment]
You actually can access solarized colors, you just made a little mistake.

```lua
solarized:setup {
  config = {
    theme = "neovim",
    transparent = true,
  },
  colors = {
   background = "#001e26" -- custom background color
  },
  highlights = function(colors, darken)
    return {
      -- NormalNC = { fg = colors.fg, bg = colors.bg }, -- default color
      NormalNC = { fg = darken(colors.fg, 10), bg = colors.background }, -- custom color
    }
  end
}
```

**Comment by vihu** [comment]
> You actually can access solarized colors, you just made a little mistake.
> 
> ```lua
> solarized:setup {
>   config = {
>     theme = "neovim",
>     transparent = true,
>   },
>   colors = {
>    background = "#001e26" -- custom background color
>   },
>   highlights = function(colors, darken)
>     return {
>       -- NormalNC = { fg = colors.fg, bg = colors.bg }, -- default color
>       NormalNC = { fg = darken(colors.fg, 10), bg = colors.background }, -- custom color
>     }
>   end
> }
> ```

Thank you for the update.

My only concern with this approach is that the background remains fixed and doesn't work well when changing between light and dark scheme. I was essentially looking to emulate something like `dim_inactive` setting, as an example [this](https://github.com/ellisonleao/gruvbox.nvim/pull/149) is how it's done for gruvbox.

**Comment by maxmx03** [comment]
> > You actually can access solarized colors, you just made a little mistake.
> > ```lua
> > solarized:setup {
> >   config = {
> >     theme = "neovim",
> >     transparent = true,
> >   },
> >   colors = {
> >    background = "#001e26" -- custom background color
> >   },
> >   highlights = function(colors, darken)
> >     return {
> >       -- NormalNC = { fg = colors.fg, bg = colors.bg }, -- default color
> >       NormalNC = { fg = darken(colors.fg, 10), bg = colors.background }, -- custom color
> >     }
> >   end
> > }
> > ```
> 
> Thank you for the update.
> 
> My only concern with this approach is that the background remains fixed and doesn't work well when changing between light and dark scheme. I was essentially looking to emulate something like `dim_inactive` setting, as an example [this](https://github.com/ellisonleao/gruvbox.nvim/pull/149) is how it's done for gruvbox.

The colorscheme will adapt its colors based on the set background option in Neovim

```lua
   solarized:setup {
        config = {
          transparent = false,
          theme = 'neovim',
        },
        highlights = function(colors)
          return {
            NormalNC = { fg = colors.comment, bg = colors.bg_alt },
          }
        end,
      }
```

https://user-images.githubusercontent.com/50273941/226135228-e9877a39-3169-4d4b-a51e-d884027ea72c.mp4

**Comment by vihu** [comment]
This works, thanks!
