### ISSUE TITLE
[Bug] Unexpected event when trying to apply_semantic_hl

### ISSUE THREAD

**Issue by vihu** [maxmx03/solarized.nvim#21]
I have the following configuration (using lazy.nvim):

```lua
return {
	"maxmx03/solarized.nvim",
	priority = 1000,
	enabled = true,
	config = function()
		local _, solarized = pcall(require, "solarized")

		solarized:setup({
			config = {
				theme = "neovim",
				transparent = true,
			},
		})

		vim.cmd("colorscheme solarized")
	end,
}

```

Getting the below error with [this](https://github.com/maxmx03/solarized.nvim/commit/888c1a20e4d0e1bfa9e797369a74f9023e55e056) commit:

![image](https://user-images.githubusercontent.com/3199183/226140000-e6fd6473-1f8f-46bd-9441-7e67e7300d65.png)

**Comment by toejough** [comment]
IDK if this is the same thing, but it feels like the same thing, and I've uninstalled and reinstalled the plugin this evening:
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/5317312/226223157-353bb979-3564-4777-96d9-31484c2b9cb6.png">

I'm new to packer, so I could be doing something wrong, too, but my config is the same as the config in this repo's README. My nvim version: 
<img width="180" alt="image" src="https://user-images.githubusercontent.com/5317312/226223287-9f1ca661-fb47-4658-970f-92800241a85b.png">

**Comment by maxmx03** [comment]
i fix it now, sorry, is because i'm using an event that is only available in neovim nightly.
