### ISSUE TITLE
[Bug] LSP floating selection not highlighted correctly

### ISSUE THREAD

**Issue by vihu** [maxmx03/solarized.nvim#23]
Hello,

Please note in the below gif that the highlights for selection when using LSP floating window don't correctly show up. I would expect that the selection is highlighted differently from the foreground/background color.

![no-selection-highligh-lsp](https://user-images.githubusercontent.com/3199183/228058305-32b4906b-8c4c-445b-b5d2-12d67533651b.gif)

**Comment by maxmx03** [comment]
Have you tested this bug with other colorschemes. 
It could be your autocompletion configuration.

https://user-images.githubusercontent.com/50273941/228299146-ff76045d-0ef1-41a8-a079-d8d44815a44b.mp4


### **try to change the `PmenuSel` background color.**

**Comment by vihu** [comment]
Thanks, I had win_highlight getting overriden in cmp settings. Removing that fixed it.
