### ISSUE TITLE
Add support for lualine

### ISSUE THREAD

**Issue by DerpGusta** [maxmx03/solarized.nvim#28]
Can you please add support for lualine colors? The auto mode looks as follows in light mode:

![image](https://user-images.githubusercontent.com/40120124/234834159-b10acc1c-3183-4c9a-b033-46bc7f029dd4.png)

**Comment by maxmx03** [comment]
there is already support for lualine, here an example:

![20230429_00h30m48s_grim](https://user-images.githubusercontent.com/50273941/235281494-83cc80d5-ba82-48da-8475-7163d26c6e55.png)

**Comment by DerpGusta** [comment]
Thank you. I didn't know that because it wasn't in the README.md either, in the supported plugins list.
Just in case, could you add a line about setting it up for future users?
