### ISSUE TITLE
Twilight support

### ISSUE THREAD

**Issue by Salam4nder** [maxmx03/solarized.nvim#3]
First of all, thank you for this wonderful theme.
Just wanted to check if Twilight support would be possible for this. At the moment, the dimmed space is just black. I'll post pictures of current vs expected to show you what I mean.
Thanks once again!
<img width="1500" alt="Screen Shot 2022-08-02 at 20 31 23 PM" src="https://user-images.githubusercontent.com/89915813/182448582-22f1c5c4-0702-46b9-bdd2-2ef9eff7f953.png">
<img width="1503" alt="Screen Shot 2022-08-02 at 20 35 08 PM" src="https://user-images.githubusercontent.com/89915813/182448671-117fb27f-d042-4404-9b61-8b7be997a8d4.png">

**Comment by maxmx03** [comment]
This what you can do for now.

```lua
solarized.setup {
  transparent = true,
  theme = 'vscode',
  mode = 'dark',
  highlights = function(colors)
    return {
      Twilight = { fg = colors.secondary, bg = 'NONE' }
    }
  end,
}
```

**Comment by maxmx03** [comment]
Sorry, i didnt see the issue until now, update the colorscheme and see if is everything is working.

**Comment by Salam4nder** [comment]
Works great now! Thank you so much and have a nice day.
