### ISSUE TITLE
Selecting a theme doesn't make any difference

### ISSUE THREAD

**Issue by Massolari** [maxmx03/solarized.nvim#33]
After update the plugin I realized that a lot changed.

Personally, I didn't like how the theme looks now and tried to change to "neo" as I was using the old "vscode" theme, but it seems there isn't any difference from the "default" one:
![image](https://github.com/maxmx03/solarized.nvim/assets/12272702/2aa19287-9a29-4d7e-bbeb-1dacffe911fd)
(Above is "neo", below is "default")

Just to let you know why I didn't like the changes, here is how it was before:
![image](https://github.com/maxmx03/solarized.nvim/assets/12272702/950a614c-fbc4-4bb4-a1d3-7107a1c3dc6d)

indent lines had a "weaker" color, syntax highlight was better (see the keyword `true`)

**Comment by maxmx03** [comment]
Can you show me your Solarized configuration?

About the indentline, is actually easy to fix

```lua
require('solarized').setup {
        highlights = function(c, helper)
          local lighten = helper.lighten

          return {
            IndentBlanklineChar = { fg = lighten(c.base01, 50) },
            IndentBlanklineContextChar = { fg = c.base01 },
          }
        end,
      }
```

![Captura de tela de 2023-06-29 12-17-02](https://github.com/maxmx03/solarized.nvim/assets/50273941/9e41b423-56f3-402a-942c-df420eb55d48)

solarized-dark neo

![Captura de tela de 2023-06-29 11-59-32](https://github.com/maxmx03/solarized.nvim/assets/50273941/426335be-4054-43b9-acb7-94d3b6d3fa51)

solarized-dark default theme

![Captura de tela de 2023-06-29 11-59-48](https://github.com/maxmx03/solarized.nvim/assets/50273941/fe4e33b2-5ad3-4a47-8955-be2970ccfd1f)

solarized-light neo dashboard

![Captura de tela de 2023-06-29 12-00-43](https://github.com/maxmx03/solarized.nvim/assets/50273941/88013e6b-0df5-49cc-9238-9b584cf3d2c7)

solarized-light default theme dashboard

![Captura de tela de 2023-06-29 12-00-30](https://github.com/maxmx03/solarized.nvim/assets/50273941/3b182de2-b244-4f7d-bf9f-68c05805f208)

solarized light neo

![Captura de tela de 2023-06-29 12-01-20](https://github.com/maxmx03/solarized.nvim/assets/50273941/90c0b397-8dfa-433b-baa1-e1d846cd1bbc)

solarized light default theme

![Captura de tela de 2023-06-29 12-01-01](https://github.com/maxmx03/solarized.nvim/assets/50273941/737d53bf-e91f-4689-aca6-d2844694cd0a)

**Comment by Massolari** [comment]
Ok, I found the issue while I was writting a response for you.

I was calling `:setup()` instead of `.setup()`, I didn't realized that you changed that too. I'm sorry.

Now I could change the theme to "neo" and your fix for the indent lines worked. Thanks for your patience and for this great theme!
