### ISSUE TITLE
fg and bg are same color for ColorColumn

### ISSUE THREAD

**Issue by modille** [maxmx03/solarized.nvim#36]
https://github.com/maxmx03/solarized.nvim/blob/8c59d890fdbf2665efa3ae25356deb964fdd2358/lua/solarized/themes/default/editor.lua#L5

I think it should just set the `bg` and not the `fg` (similar to CursorColumn), right? otherwise characters that occur in the colorcolumn are invisible lol

with that said, thank you so much for this theme! ❤️ I've tried a half dozen solarized nvim themes over the past couple years. this one right now (even before the recent refactor) is hands-down the best. well done! 🙌

**Comment by maxmx03** [comment]
i will fix 😅
