### ISSUE TITLE
Switch between dark & light?

### ISSUE THREAD

**Issue by travisariggs** [maxmx03/solarized.nvim#4]
First, thank you very much for this excellent color scheme!

This is not necessarily an issue with the code; maybe just documentation.

Is there a way to switch back and forth between the dark and light versions of your theme?

I tried running solarize's setup from neovim's command line and passing in either 'dark' or 'light', but didn't have any luck.

Again, thanks for the excellent theme.

**Comment by maxmx03** [comment]
Here an example

## Dark theme
```lua
local success, solarized = pcall(require, 'solarized')

if not success then
  return
end

solarized.setup {
 mode = 'dark',
 theme = 'neovim'
}

vim.cmd 'colorscheme solarized'
```

## Light Theme
```lua
local success, solarized = pcall(require, 'solarized')

if not success then
  return
end

solarized.setup {
 mode = 'light',
 theme = 'neovim'
}

vim.cmd 'colorscheme solarized'
```
