### ISSUE TITLE
Neo light theme and contrast

### ISSUE THREAD

**Issue by redstreet** [maxmx03/solarized.nvim#44]
The neo light theme seems to have low contrast on things like search, tabline, and such, making it hard to read. Is this by design? If not, I'd be happy to send a PR to fix some of these, since I imagine these are issues that affect everyone. This involves color selection for various elements, and I'm not sure if you're open to such a PR? Thanks!

**Comment by maxmx03** [comment]
Thank you for your feedback and willingness to contribute! I welcome your PR for the light theme, but please make changes in the dev branch first. Feel free to submit it, and I'll review it. I have already attempted to fix the IncSearch issue, so please take a look later.

**Comment by redstreet** [comment]
Great, will push to `dev` soon.
