### ISSUE TITLE
Matching term + current selection in telescope makes things hard to read

### ISSUE THREAD

**Issue by mtrudel** [maxmx03/solarized.nvim#45]
First up, thanks for a great theme! I've been a diehard Solarized user for over a decade & this is probably the best application of it I've seen in any environment. Well done.

I'm having an issue with the solarized theme in my install whereby the matched characters in a telescope window (which set the foreground) combine badly with the current selection (which sets the background) and result in making the exact text you want to look at in the window very hard to discern. Here's a screenshot; note how the selected `install.zsh` line is nearly impossible to read:

<img width="762" alt="image" src="https://github.com/maxmx03/solarized.nvim/assets/79646/200f1b75-1a9a-4901-8d84-666a38460f25">

I looked at telescope plugin highlights in the theme but I don't think I see a relevant highlight that would cover this (though truthfully, highlights are at the distant edge of my knowledge of vim config).

I'm not sure what the best approach would be:

* Use a better color for matching characters within a selection
* Disable matching characters on the selected item
* Something else?

My config is near-default & exactly the contents of my dotfiles repo, most notably my [solarized](https://github.com/mtrudel/dotfiles/blob/main/nvim/config/lua/lazy_plugins/solarized.lua) & [telescope](https://github.com/mtrudel/dotfiles/blob/main/nvim/config/lua/lazy_plugins/telescope.lua) configs.

Neovim 0.8.3, running on iTerm (also using a Solarized scheme, not that truecolor cares).

**Comment by mtrudel** [comment]
I've since added an override of

```lua
highlights = function(colors)
         return {
           TelescopeMatching = { fg = colors.base3, },
         }
       end
``` 

and it looks much better IMO:

<img width="922" alt="image" src="https://github.com/maxmx03/solarized.nvim/assets/79646/bf66515b-a4fa-4c11-bb8b-222fae086f4f">

<img width="922" alt="image" src="https://github.com/maxmx03/solarized.nvim/assets/79646/96665d4a-a64d-4bf4-8856-e0b33f918f0e">

Not at visually flashy but definitely more functional. Perhaps we could make this the default value for that highlight?

**Comment by maxmx03** [comment]
Fixed 😄, thank you for your feedback.

[commit](https://github.com/maxmx03/solarized.nvim/commit/85ac187a2339b058e76d89828803fccb416de16d)

**Comment by mtrudel** [comment]
Even nicer! 

<img width="762" alt="image" src="https://github.com/maxmx03/solarized.nvim/assets/79646/082f96ad-74e2-4e2f-a95a-6fb02af7e5be">

Thanks so much!
