### ISSUE TITLE
Methods being italized, apparently because of identifier

### ISSUE THREAD

**Issue by dgmora** [maxmx03/solarized.nvim#47]
It's not clear to me if this is because of the theme. I've just enabled italics for tmux + alacritty.

Most methods are italized because of `Identifier`. I can remove this by doing `:highlight Identifier gui=NONE`. But I was wondering if this could be fixed, or if it was intended. I've tried  this as well:

```lua
      styles = {
        functions = { italic = false },
      },
```

Here's an example:

<img width="126" alt="Screenshot 2023-10-22 at 13 39 17" src="https://github.com/maxmx03/solarized.nvim/assets/3609616/a93f5c6a-ebaa-47f3-9ac5-3b624f289d7e">

This is what I get when I use `Inspect`:

```
Treesitter
  - @variable.ruby links to Identifier ruby
  - @function.ruby links to Function ruby

Semantic Tokens
  - @lsp.type.method.ruby links to Function priority: 125
  - @lsp.mod.declaration.ruby links to @lsp priority: 126
  - @lsp.typemod.method.declaration.ruby links to @lsp priority: 127

Extmarks
  - IlluminatedWordRead illuminate.highlight
```

Some more screenshots in the documentation could help diagnose if things looked how they're supposed to look :)

**Comment by maxmx03** [comment]
I fixed it in the dev branch by removing the default styles for Identifier and Function, and then I'll merge it into the main branch.
