### ISSUE TITLE
Change background without restarting neovim?

### ISSUE THREAD

**Issue by travisariggs** [maxmx03/solarized.nvim#5]
I can change the background of your colorscheme from dark to light by setting the setup `mode` to "dark" or "light" in my neovim configuration files.

But is there a Neovim command to dynamically switch the background without restarting Neovim?

When I have it configured as a dark background, I tried this while running Neovim to switch the background to light mode, but it had no effect.

```
:lua require("solarized").setup({mode='light', theme='neovim', transparent='false'})
```

I then tried `:colorscheme solarized` in hopes that it would reload the colorscheme, but that had no effect either.

**Comment by maxmx03** [comment]
Hello! I just wanted to let you know that I've made some improvements, based on your feedback. Specifically, I've added the ability to change the background from dark to light with the press of a button.

To test this out, please try pressing F2 to switch to the dark background and F3 to switch to the light background. Let me know if there are any issues or if everything is working properly.

```lua
  {
    'maxmx03/solarized.nvim',
    branch = '5-change-background-without-restarting-neovim',
    config = function()
      local solarized = require 'solarized'

      vim.o.background = 'dark'

      solarized.setup {
        theme = 'neovim',
        transparent = false,
      }

      local opts = { noremap = true, silent = true }

      vim.keymap.set('n', '<F2>', ':set background=light<cr>', opts)
      vim.keymap.set('n', '<F3>', ':set background=dark<cr>', opts)
    end,
  },
```
