### ISSUE TITLE
Double configuration check causes setup failure

### ISSUE THREAD

**Issue by mteit** [maxmx03/solarized.nvim#53]
**Issue Description:**

The following code snippet in `.config/nvim/init.lua` is not functioning as expected:

```lua
require('solarized').setup {
  theme = 'neo'
}
```

This issue arises because the `require('solarized').setup` function is called twice, causing the `M.is_configured` flag to be set to `true`. Consequently, the double configuration check prevents the intended setup.

**Proposed Solution:**

To resolve this issue, consider removing the redundant double configure checking. The provided solution involves modifying the `lua/solarized/init.lua` file. The changes are as follows:

```diff
diff --git a/lua/solarized/init.lua b/lua/solarized/init.lua
index 85b5499..7279993 100644
--- a/lua/solarized/init.lua
+++ b/lua/solarized/init.lua
@@ -3,7 +3,6 @@ local solarized_palette = require('solarized.palette')
 local solarized_highlights = require('solarized.highlights')
 
 local M = {}
-M.is_configured = false
 M.has_set_highlights = false
 M.config = {}
 
@@ -35,11 +34,8 @@ function M.setup(user_config)
   vim.o.termguicolors = true
   vim.g.colors_name = 'solarized'
 
-  if not M.is_configured then
-    local default_config = solarized_config()
-    M.config = vim.tbl_deep_extend('force', default_config, user_config or {})
-    M.is_configured = true
-  end
+  local default_config = solarized_config()
+  M.config = vim.tbl_deep_extend('force', default_config, user_config or {})
   local colors = solarized_palette.get_colors()
```

This solution eliminates the redundant configuration check, ensuring proper execution of the `require('solarized').setup` function.

**Comment by maxmx03** [comment]
The issue has been resolved in the dev branch; therefore, I will soon merge it into the main branch.

**Comment by mteit** [comment]
Thank you for your reply. 
The current state of the `solarized.setup` method is causing a critical issue for users, including myself. The proposed solution, while cautious, is essential for restoring functionality.

I can try to work on a solution, but I need a better understanding of the logic relying on the `M.is_configured` variable. Can you explain why you are using this logic?

**Comment by maxmx03** [comment]
> Thank you for your reply. The current state of the `solarized.setup` method is causing a critical issue for users, including myself. The proposed solution, while cautious, is essential for restoring functionality.
> 
> I can try to work on a solution, but I need a better understanding of the logic relying on the `M.is_configured` variable. Can you explain why you are using this logic?

"I think I found a good solution; I moved part of the logic to another function called 'load' and then replaced 'setup' with 'load' in the 'colors'. I believe that, this way, 'setup' is only used to store the user's configuration.

You can find the changes in the 'dev' branch.

`init.lua`
```lua
function M.load()
  if vim.g.colors_name then
    vim.cmd('hi clear')
  end

  if vim.fn.exists('syntax_on') then
    vim.cmd('syntax reset')
  end

  vim.o.termguicolors = true
  vim.g.colors_name = 'solarized'

  local default_config = solarized_config()
  local colors = solarized_palette.get_colors()
  solarized_highlights(M.colors or colors, M.config or default_config)
end
```
`init.lua`
```lua
function M.setup(opts)
  local default_config = solarized_config()
  M.config = vim.tbl_deep_extend('force', default_config, opts or {})
  local colors = solarized_palette.get_colors()

  if type(M.config.colors) == 'table' and not vim.tbl_isempty(M.config.colors) then
    M.colors = solarized_palette.extend_colors(colors, M.config.colors)
  elseif type(M.config.colors) == 'function' then
    local colorhelper = require('solarized.utils.colors')
    M.colors = solarized_palette.extend_colors(colors, M.config.colors(colors, colorhelper))
  end
end
```

`colors/solarized.vim`
```vim
lua << EOF
require('solarized').load()
EOF
```

**Comment by mteit** [comment]
Thank you for the swift resolution! I've reviewed the changes, and the updated approach with the `load` function looks well. It really works in my configuration, and I appreciate the effort you've put into finding a solution.
