### ISSUE TITLE
Rename solarized.lua theme for lualine to avoid name collision

### ISSUE THREAD

**Issue by mteit** [maxmx03/solarized.nvim#55]
**Issue Description:**

The current implementation of the solarized theme for the `lualine` plugin uses the same filename (`solarized.lua`) as the theme from the basic `lualine` theme library. This leads to unintended behavior, where enabling the solarized theme from the solarized library loads the theme from the basic `lualine` library instead.

**Proposed Solution:**

I propose renaming the file from `/solarized.nvim/lua/lualine/themes/solarized.lua` to `/solarized.nvim/lua/lualine/themes/solarized-maxmx03.lua`. This will prevent name collisions and ensure that the solarized theme from the solarized library is correctly utilized.

**Comment by maxmx03** [comment]
I believe this might not be a significant issue. If a user installs my colorscheme and configures the lualine theme to utilize Solarized, lualine will automatically select the theme from my colorscheme. However, if the user prefers not to use the theme provided by solarized.nvim, they can manually import it from lualine as shown below:

```lua
require('lualine').setup {
    options = {
        theme = require('lualine.themes.solarized')
    }
}
```
