### ISSUE TITLE
Configuring highlight of type "@variable"

### ISSUE THREAD

**Issue by hdemers** [maxmx03/solarized.nvim#69]
First, thank you for such a nice colorscheme! Really well done. I especially like the way we can easily configure it using the highlight option:
```lua
require('solarized').setup {
    highlights = function (colors, colorhelper)
        local darken = colorhelper.darken
        local lighten = colorhelper.lighten
        local blend = colorhelper.blend

        return {
            LineNr = { fg = c.base1, bg = c.base02 },
            CursorLineNr = { bg = c.base02 },
            CursorLine = { bg = c.base02 },
            Function = { italic = false },
            Visual = { bg = c.cyan },
        }
    end
}
```

I'd like to know what's your recommended approach to configure highlights that start with an @ sign, like @variable? Thanks again.

**Comment by maxmx03** [comment]
```lua
require('solarized').setup {
    highlights = function ()
        return {
          ['@character.printf'] = { link = '@keyword' },
        }
    end
}
```

**Comment by hdemers** [comment]
Gotcha. I should have mentioned that I actually tried that, and it appeared to work, in the sense that the highlight was changed, but it was reported by `:highlight` as the following, assuming I did:
```lua
require('solarized').setup {
    highlights = function ()
        return {
          ['@function.builtin'] = { link = 'Special' },
        }
    end
}
```


![image](https://github.com/maxmx03/solarized.nvim/assets/474259/1547b030-1c43-4f3f-bdbb-67e92b95c4bb)

Is that how it should be?

**Comment by maxmx03** [comment]
I will take a look later, but links have high priority even if there are guifg or guibg colors. Nothing to worry about.
