### ISSUE TITLE
Change highlighting of symbol under cursor

### ISSUE THREAD

**Issue by andcov** [maxmx03/solarized.nvim#76]
First of all, thank you for the beautiful colorscheme, I have started using it everywhere.

I was wondering if it is possible to change the way the character and the symbol under the cursor are highlighted. Currently, the char under the cursor maintains its bg and fg, while the rest of the symbol (and all other occurrences of the symbol) get inverted. Is is possible to instead invert the current char, maintain the font colour for the rest of the symbol, and maybe lightly highlight the bg.

For example, this is how Solarized looks when the cursor is over the keyword "vim":

![SCR-20240402-mmzn](https://github.com/maxmx03/solarized.nvim/assets/18496943/e7f98be3-0323-4175-b8a9-a85b24be6b41)

while this is how [OnedarkPro](https://github.com/olimorris/onedarkpro.nvim?tab=readme-ov-file) looks like:

![SCR-20240402-mnsr](https://github.com/maxmx03/solarized.nvim/assets/18496943/4e377440-f4b2-4868-bfb7-cf513f88a276)

I tried looking into the source code for an answer, but I am quite new to NeoVim and Lua, so I was not able to find much. I am using [kickstart](https://github.com/nvim-lua/kickstart.nvim/tree/19afab164183a5e80d8f7e7ae9df6b57e26a4a48) with some basic modifications as a config.

**Comment by maxmx03** [comment]
There are two ways to fix this, you can use a plugin, such as [mini-cursor](https://github.com/echasnovski/mini.cursorword) or [RRethy/vim-illuminate](https://github.com/RRethy/vim-illuminate) , or you can be use `:h vim.lsp.buf.document_highlight`.

**Comment by mekedron** [comment]
Hello @andcov! I've noticed the same problem in my LazyVim configuration. The cursor is really hard to distinguish from the background with default solarized theme.

However, by changing highlight color I could achieve this result:

Before:
<img width="861" alt="image" src="https://github.com/user-attachments/assets/d64c3b2b-625d-47c8-885b-24ba9c8bd1c6">

After:
<img width="825" alt="image" src="https://github.com/user-attachments/assets/37798451-09af-448f-907e-c9d22b8b6bb4">

The code:
```
  { 
    "maxmx03/solarized.nvim",
    opts = {
      highlights = function (c)
        return {
          Visual = { bg = c.base1, fg = "#cccdfb" },
        }
      end
    }
  }
```

Hope it helps!
