### ISSUE TITLE
Warning messages not printed

### ISSUE THREAD

**Issue by abgeana** [maxmx03/solarized.nvim#84]
I am using Neovim v0.10.1 on macOS, together with the lazy plugin manager. I tried with/without tmux, in both alacritty and the default terminal application.

I noticed the warning message

```
W325: Ignoring swapfile from Nvim process xxx
```

does not appear anymore when I enable this colorscheme. This warning message normally appears when the same file is opened in a second Neovim process.

Later edit - sometimes the warning message does appear, but only for a split second.

Minimal config to reproduce, in a `plugins/colorscheme.lua` file

```lua
return {
    'maxmx03/solarized.nvim',
    lazy = false,
    priority = 1000,

    config = function()
        vim.cmd.colorscheme 'solarized'
    end,
}
```

**Comment by maxmx03** [comment]
I have no idea what this error message is. Maybe it's caused by another plugin.
