### ISSUE TITLE
3.0 -> 3.1 Upgrade Changes Colors

### ISSUE THREAD

**Issue by xanderdunn** [maxmx03/solarized.nvim#88]
On solarized.nvim 3.0:
<img width="1496" alt="Screenshot 2024-08-27 at 13 55 33" src="https://github.com/user-attachments/assets/c304d795-bd4c-4f45-a0a0-192d5a2383b2">

After upgrading to 3.1:
<img width="1496" alt="Screenshot 2024-08-27 at 13 56 36" src="https://github.com/user-attachments/assets/5f8ae87d-ca13-42f8-9045-3e6d5ba53077">

I would expect the colors on top to be correct. How do I return to them?

Notice that the solarized config is in the above screenshots, and it's the same on both, except for the pinned version number:
```lua
	{
		"maxmx03/solarized.nvim",
		version = "3.0",
		lazy = false,
		priority = 1000,
		---@type solarized.config
		opts = {},
		config = function(_, opts)
			vim.o.termguicolors = true
			vim.o.background = "dark"
			require("solarized").setup(opts)
			vim.cmd.colorscheme("solarized")
		end,
	}, -- solarized color scheme
```

```
$ nvim --version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1724512491
Run "nvim -V1 -v" for more info
```

I noticed some configuration changes in the [release notes of the 3.1 update](https://github.com/maxmx03/solarized.nvim/releases/tag/v3.1.0), but I don't believe I'm using any of those config options.

This reproduces for me on both Ubuntu 22.04 and macOS Sonoma.

**Comment by maxmx03** [comment]
Use standout. Then, set the foreground color to 'NONE' to remove the default foreground:

```lua
    on_highlights = function(colors)
      ---@type solarized.highlights
      local groups = {
        Visual = { bg = colors.base02, standout = true, fg = 'NONE' },
      }
      return groups
    end,

```

**Comment by xanderdunn** [comment]
Thanks! That returns specifically the visual highlight to its original function, but notice there are still many colors here that have changed:
<img width="1496" alt="Screenshot 2024-08-27 at 15 35 42" src="https://github.com/user-attachments/assets/1c0bf188-62c4-4125-a365-c59d66734efb">

- `false` and `1000` under the visual highlight are purple rather than green and pink
- The in-line info messages off to the right side are grey rather than blue
- Some words are purple rather than green. Look for example at the `vim` in `vim.o.background.`

The differences might be clearer in this bash file. In 3.0:
<img width="1496" alt="Screenshot 2024-08-27 at 15 38 51" src="https://github.com/user-attachments/assets/a6d42fb6-3ae5-4b0b-b716-6b51691f180e">

In 3.1:
<img width="1496" alt="Screenshot 2024-08-27 at 15 38 42" src="https://github.com/user-attachments/assets/41111fa3-14b0-4fd3-8f77-ba0338b27107">

**Comment by maxmx03** [comment]
The reason for this is that you aren't using [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter). Here's how it looks with Tree-sitter enabled:

![Captura de tela de 2024-08-27 20-52-37](https://github.com/user-attachments/assets/cf79900e-766b-431e-90ed-ec76a449a706)

Alternatively, you can stick with version 3.0 for now and update later if the highlight groups appear outdated.

**Comment by maxmx03** [comment]
Try updating to the latest version and see if it resolves the issue.

**Comment by xanderdunn** [comment]
I should be using nvim-treesitter. I have it installed via Lazy plugin manager:
```
	{ "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
	{ "nvim-treesitter/nvim-treesitter-context" },
```

And it's loaded:
<img width="566" alt="Screenshot 2024-08-27 at 18 47 21" src="https://github.com/user-attachments/assets/dc2650ea-1691-4f07-8fbb-de087b952abb">

In addition, I has the language-specific packages installed:
```lua
require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"c",
		"lua",
		"vim",
		"vimdoc",
		"query",
		"markdown",
		"markdown_inline",
		"rust",
		"python",
		"cpp",
		"asm",
	},
	auto_install = true,
})

```

Is there something additional I need to get treesitter integration working? I still see this on solarized v3.1.1:
<img width="1496" alt="Screenshot 2024-08-27 at 18 55 56" src="https://github.com/user-attachments/assets/647910da-23c9-4611-85db-08dcb6a56bb0">

Updating to latest main (cba648c) seems to largely fix it:
<img width="1496" alt="Screenshot 2024-08-27 at 18 57 01" src="https://github.com/user-attachments/assets/8c0d6918-cfda-47c0-be1f-018398a2e4d6">
Notice that some colors are still different compared to v3.0. Some reds are purple, and the inline info messages went from blue to grey. Is this intentional?

**Comment by maxmx03** [comment]
I've reviewed the [default Treesitter configuration](https://github.com/nvim-treesitter/nvim-treesitter/blob/2eb50352c039009cf046f43241b649b162ee5148/lua/nvim-treesitter/configs.lua#L52) and noticed that syntax highlighting is disabled by default.

```lua
  require('nvim-treesitter.configs').setup {
        auto_install = true,
        sync_install = false,
	ensure_installed = {
		"c",
		"lua",
		"vim",
		"vimdoc",
		"query",
		"markdown",
		"markdown_inline",
		"rust",
		"python",
		"cpp",
		"asm",
	},
        highlight = {
          enable = true, -- <-- need's to be enabled
          additional_vim_regex_highlighting = false,
        },
      }
```
