### ISSUE TITLE
bring neo colorscheme back

### ISSUE THREAD

**Issue by jabuxas** [maxmx03/solarized.nvim#90]
why was it removed?

**Comment by jabuxas** [comment]
> Currently, the Neo variant is practically the Solarized Light theme

how so? do you mean that default white is almost equal as the neo white of before?

> Fortunately, I’ve designed the colorscheme to be customizable, allowing users to create their own theme variants as well.

yes, thank you a lot, i updated from a somewhat old update and was really surprised by the amount of new stuff, it only bummed me that the neo variant doesn't really exist anymore.

i know i can tweak the theme to get the same variant again, are you able to point out which commit deleted neo variant? that would make things easier for me to recreate it

ty a lot

**Comment by maxmx03** [comment]
[v3.0.0](https://github.com/maxmx03/solarized.nvim/tree/v3.0.0)

**Comment by jabuxas** [comment]
ain't that a lot of highlights... gonna be a tough job
