### ISSUE TITLE
Change back to initial color for left side of the screen

### ISSUE THREAD

**Issue by aragalie** [maxmx03/solarized.nvim#93]
Hey! Thanks a lot for your work on this @maxmx03, I really like the theme! 🙏

And nice that you're reworking the approach as well.

One small thing: could you please be so kind and let me know how can I change the color of the left side of the buffer, where the numbers are shown, and make it either transparent or the same as the background?

Personally I prefer much more how it was before (you can see it in the initial screenshots of the README in your repo), where this part was the same color as the background/rest of the buffer...

<img width="479" alt="Screenshot 2024-09-02 at 11 36 51" src="https://github.com/user-attachments/assets/36488bda-b27e-4a84-bd8d-bbe2ca7cec31">

**Comment by maxmx03** [comment]
You may need to change the `SignColumn`, `LineNr`, and `CursorLineNr` highlight groups, and possibly the diagnostic signs highlight groups (`h:diagnostic-highlights`)

```lua
opts = {
  'maxmx03/solarized.nvim',
  lazy = false,
  priority = 1000,
  ---@type solarized.config
  opts = {
    on_highlights = function(colors)
      return {
        SignColumn = { bg = colors.base03 },
        LineNr = { bg = colors.base03 },
        CursorLineNr = { bg = colors.base03 },
      }
    end
  },
  config = function(_, opts)
    require('solarized').setup(opts)
    vim.cmd.colorscheme 'solarized'
  end,
}
```

**Comment by aragalie** [comment]
Yup, that did it, thanks a lot! 🙏

Perhaps these instructions can also be added to the `README`, just in case others have the same issue?
